config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    users: 'users/users',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "admin/users#index"
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :admin do
      root 'home_page#index', as: 'admin_home'

      resources :users, except: %i[show]
      patch 'users/change_permissions/:id', to: 'users#change_permissions', as: 'change_user_permissions'
      patch 'users/change_status/:id', to: 'users#change_status', as: 'change_user_status'
      get 'users/export', to: 'users#export_users', as: 'export_users'

      resources :categories
      resources :sub_categories
      resources :teams
      resources :articles

      get 'information-architecture', to: 'information_architecture#index'

      get 'sport-live/teams', to: 'sport_live_bar#teams'
      get 'sport-live/players', to: 'sport_live_bar#players'

      root "users#index"
    end
  end

  draw(:api)
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :uuid             not null, primary key
#  first_name             :string           not null
#  last_name              :string           not null
#  email                  :string           not null
#  encrypted_password     :string           not null
#  remember_created_at    :datetime
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  status                 :integer          default("active")
#  is_admin               :boolean          default(FALSE)
#  created_at             :datetime
#  updated_at             :datetime
#  provider               :string
#  uid                    :string
#
# User model
class User < ApplicationRecord

  enum status: { active: 1, blocked: 0 }
  enum role: { customer: 0, manager: 1, admin: 2 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  validates :first_name, presence: true
  validates :last_name, presence: true

  include Searchable

  scope :admin, -> { where(is_admin: true) }
  scope :simple_user, -> { where(is_admin: false) }
  scope :online, -> { where('current_sign_in_at >= last_sign_in_at') }
  scope :offline, -> { where('current_sign_in_at < last_sign_in_at') }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name
      user.last_name = auth.info.name
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] &&
                session['devise.facebook_data']['extra']['raw_info'] &&
                user.email.blank?
        user.email = data['email']
      end
    end
  end

  def online?
    current_sign_in_at.present? ? current_sign_in_at >= last_sign_in_at : false
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.export_attributes
    %w{id email full_name}
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  # UsersController
  class UsersController < BaseController
    before_action :set_user, only: %i[show edit update destroy change_permissions change_status]
    before_action :set_title

    def index
      @simple_users = get_user_service.call(params, 'simple_users')
      @admin_users = get_user_service.call(params.slice(:q), 'admins')

      @selected_user = user_service.get_selected_user(params, @simple_users, @admin_users)

      @tab = params[:tab] || 'users'
    end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path, notice: t('user_was_successfully_updated.')
      else
        redirect_to admin_users_path, notice: t('user_was_not_updated.')
      end
    end

    def destroy
      if @user != current_user
        @user.destroy
        redirect_to admin_users_path, notice: t('user_was_successfully_destroyed.')
      else
        flash[:error] = t('you_cannot_delete_the_current_user.')
        redirect_to admin_users_path
      end
    end

    def change_permissions
      result = UserManagement::ChangeUserPermissions.call(user: @user, current_user: current_user,)

      if result.success?
        redirect_to admin_users_path, notice: t('user_was_successfully_change_permissions.')
      elsif result.error == UserManagement::SendMail::FAIL_SEND_MAIL
        redirect_to admin_users_path, notice: t('user_was_successfully_change_status_but_not_sent_a_email.')
      else
        redirect_to admin_users_path, notice: t('user_was_no_change_permissions.')
      end
    end

    def change_status
      result = UserManagement::ChangeUserStatus.call(
        current_user: current_user,
        user: @user,
        params: user_params
      )

      if result.success?
        flash[:notice] = t('user_was_successfully_change_status.')
      elsif result.error == UserManagement::SendMail::FAIL_SEND_MAIL
        flash[:error] = t('user_was_successfully_change_status_but_not_sent_a_email.')
      else
        flash[:error] = t('user_was_not_change_status.')
      end

      redirect_to admin_users_path
    end

    def export_users
      ExportWorker.perform_async(current_user.id, 'User', params[:type], 'users')
      flash[:notice] = t('export_started.')

      redirect_to admin_users_path
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :status)
    end

    def user_service
      @user_service ||= UserService.new
    end

    def get_user_service
      @get_user_service ||= UserManager::GetUsersService.new
    end

    def set_title
      @page_title = t('users')
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :verify_authenticity_token, only: :facebook

    def facebook
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
      else
        session['devise.facebook_data'] = request.env['omniauth.auth'].except(:extra)
        redirect_to new_user_registration_url
      end
    end

    def google_oauth2
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra')
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
    end

    def failure
      redirect_to root_path
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[attribute first_name last_name])
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    def create
      user = User.find_by(email: user_params[:email])
      flash[:error] = t('user_is_not_exist.') unless user
      super
    end

    # DELETE /resource/sign_out
    def destroy
      current_user.update_attribute(:last_sign_in_at, Time.now)
      super
    end

    private

    def user_params
      params.require(:user).permit(:email)
    end
  end
end

app/helpers/users/users_helper.rb
# frozen_string_literal: true

module Users
  module UsersHelper
    def get_provider_url(provider)
      case provider
      when :facebook
        user_facebook_omniauth_authorize_path
      when :google_oauth2
        user_google_oauth2_omniauth_authorize_path
      end
    end

    def get_reverse_user_status(user)
      user.active? ? 'blocked' : 'active'
    end

    def get_reverse_user_status_for_view(user)
      user.active? ? 'block' : 'activate'
    end

    def get_full_name(user)
      user.first_name + ' ' + user.last_name
    end
  end
end

app/views/admin/users/index.html.slim
.people
  div.alert.alert-success#export-message style="display: none"
  = link_to "Export CSV", admin_export_users_path(type: :csv)
  = link_to "Export XLSX", admin_export_users_path(type: :xlsx)
  = link_to "Export PDF", admin_export_users_path(type: :pdf)
  .col-lg-6.list-of-users
    ul.nav.nav-tabs
      li.nav-item.users-tab class=(@tab == 'users' ? 'active' : '')
        = link_to "users (#{@simple_users.length})", '#users', data: { toggle: 'tab', target: '#users' }

      li.nav-item.admins-tab class=(@tab == 'admins' ? 'active' : '')
        = link_to "admins (#{@admin_users.length})", '#admins', data: { toggle: 'tab', target: '#admins' }, id: 'admins-tab2'
      li.people-search
        = form_tag(current_page_params, method: :get) do
          = current_page_params(param_for: 'form', except: ['q'])
          input id="search" name="q" type="text" placeholder="search"
          i class="bi bi-search fa-lg" id="search_submit"
    .tab-content
      .tab-pane.fade.in#users class=(@tab == 'users' ? 'active' : '')
        table.table.table-sm.table-hover
          thead.thead-light
            tr
              th scope="col" = t('name')
              th scope="col" = t('status')
              th.col-md-3 scope="col"
                = t('actions')
                div.dropdown.display-inline-block.people-filter
                  = link_to '',
                          class: 'btn dropdown-toggle',
                          role: 'button',
                          aria: { haspopup: true, expanded: false },
                          data: { toggle: 'dropdown' } do
                    i class="bi bi-funnel-fill"
                  ul.dropdown-menu
                    li.dropdown-title
                      b = t('sort_by')
                    li role="separator" class="divider"
                    li
                      = link_to t('active'),
                              current_page_params.merge(filter: 'active'),
                              class: 'btn filter-active'
                    li
                      = link_to t('blocked'),
                              current_page_params.merge(filter: 'blocked'),
                              class: 'btn filter-blocked'
                    li
                      = link_to t('online'),
                              current_page_params.merge(filter: 'online'),
                              class: 'btn'
                    li
                      = link_to t('offline'),
                              current_page_params.merge(filter: 'offline'),
                              class: 'btn'

          tbody
            - @simple_users.each do |user|
              tr.clickable-row
                td scope="row"
                  = link_to current_page_params.merge(tab: 'users', selected_user: user)
                    div style="height:100%;width:100%"
                      b = get_full_name(user)
                td class=(user.active? ? 'text-color-green' : '') = user.status
                td class=(user.active? ? 'col-green' : '')
                  div.dropdown.user-actions
                    = link_to '',
                            class: 'btn dropdown-toggle',
                            role: 'button',
                            aria: { haspopup: true, expanded: false },
                            data: { toggle: 'dropdown' }
                      = t(user.status)
                      span class="caret"
                    ul.dropdown-menu
                      li
                        = link_to t('delete'),
                                admin_user_path(user),
                                remote: true,
                                class: 'btn col-red',
                                data: { confirm: 'Are you sure?' },
                                method: :delete
                      li
                        = link_to t(get_reverse_user_status_for_view(user)),
                                admin_change_user_status_path(user, user: { status: get_reverse_user_status(user) }),
                                remote: true,
                                class: (user.active? ? 'btn col-gray' : 'btn'),
                                method: :patch
                      li
                        = link_to t('make_as_admin'),
                                admin_change_user_permissions_path(user),
                                remote: true,
                                class: 'btn col-blue',
                                method: :patch

      .tab-pane#admins class=(@tab == 'admins' ? 'active' : '')
        table.table.table-sm
          thead.thead-light
            tr
              th scope="col" = t('name')
              th scope="col" = t('status')
              th.col-md-1 scope="col" = t('actions')

          tbody
            - @admin_users.each do |user|
              tr.clickable-row
                td scope="row"
                  = link_to current_page_params.merge(tab: 'admins', selected_user: user)
                    div style="height:100%;width:100%"
                      b = get_full_name(user)
                td class=(user.active? ? 'text-color-green' : '') = user.status
                td.col-red
                  div.dropdown.user-actions
                    = link_to '',
                            class: 'btn dropdown-toggle',
                            role: 'button',
                            aria: { haspopup: true, expanded: false },
                            data: { toggle: 'dropdown' }
                      = t('remove_from_admin')
                      span class="caret"
                    ul.dropdown-menu
                      li
                        = link_to t('remove_from_admin'),
                                admin_change_user_permissions_path(user),
                                remote: true,
                                class: 'btn col-red',
                                method: :patch
                      li
                        = link_to t('delete'),
                                admin_user_path(user),
                                remote: true,
                                class: 'btn col-gray',
                                data: { confirm: 'Are you sure?' },
                                method: :delete
  - if @simple_users.present?
    .col-lg-3.general-info-tabs
      ul.nav.nav-tabs
        li.active
          = link_to t("general info"), '#general-info', data: { toggle: 'tab', target: '#general-info' }

        li
          = link_to t("teams"), '#teams', data: { toggle: 'tab', target: '#teams' }
      .tab-content
        .tab-pane.fade.in.active#general-info
          div class="row user-info"
            div class='icon-container'
              img src="https://cdn2.iconfinder.com/data/icons/flatfaces-everyday-people-square/128/beard_male_man_face_avatar-512.png"
              - if @selected_user.online?
                div class='status-circle'
          div class="row user-info"
            div class="col-lg-12 full-name"
              b = get_full_name(@selected_user)
          div class="row user-info"
            div class="col-lg-6"
              b = t('registered')
            div class="col-lg-6"
              = @selected_user.created_at
          div class="row user-info"
            div class="col-lg-6"
              b = t('passed_surveys')
            div class="col-lg-6"
              | 22
          div class="row user-info"
            div class="col-lg-6"
              b = t('teams')
            div class="col-lg-6"
              | 6

        .tab-pane#teams
          div class="overflow-auto teams-list"
            ul class="list-group"
              li.list-group-item#team-list-title
                = t('team_name') + ' (6)'
              li class="list-group-item"
                div class='team-image-container'
                  img src="https://cdn2.iconfinder.com/data/icons/flatfaces-everyday-people-square/128/beard_male_man_face_avatar-512.png"
                | Cras justo odio
              li class="list-group-item"
                div class='team-image-container'
                  img src="https://cdn2.iconfinder.com/data/icons/flatfaces-everyday-people-square/128/beard_male_man_face_avatar-512.png"
                | Dapibus ac facilisis in
              li class="list-group-item"
                div class='team-image-container'
                  img src="https://cdn2.iconfinder.com/data/icons/flatfaces-everyday-people-square/128/beard_male_man_face_avatar-512.png"
                | Morbi leo risus
              li class="list-group-item"
                div class='team-image-container'
                  img src="https://cdn2.iconfinder.com/data/icons/flatfaces-everyday-people-square/128/beard_male_man_face_avatar-512.png"
                | Porta ac consectetur ac
              li class="list-group-item"
                div class='team-image-container'
                  img src="https://cdn2.iconfinder.com/data/icons/flatfaces-everyday-people-square/128/beard_male_man_face_avatar-512.png"
                | Vestibulum at eros
              li class="list-group-item"
                div class='team-image-container'
                  img src="https://cdn2.iconfinder.com/data/icons/flatfaces-everyday-people-square/128/beard_male_man_face_avatar-512.png"
                | Porta ac consectetur ac