config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    users: 'users/users',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "admin/users#index"
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :admin do
      root 'home_page#index', as: 'admin_home'

      resources :users, except: %i[show]
      patch 'users/change_permissions/:id', to: 'users#change_permissions', as: 'change_user_permissions'
      patch 'users/change_status/:id', to: 'users#change_status', as: 'change_user_status'
      get 'users/export', to: 'users#export_users', as: 'export_users'

      resources :categories
      resources :sub_categories
      resources :teams
      resources :articles

      get 'information-architecture', to: 'information_architecture#index'

      get 'sport-live/teams', to: 'sport_live_bar#teams'
      get 'sport-live/players', to: 'sport_live_bar#players'

      root "users#index"
    end
  end

  draw(:api)
end

app/views/layouts/_footer.html.slim
footer.page-footer.font-small.mdb-color.pt-4
  .row.d-flex.align-items-center.footer-row
    .col-md-6.float-left
      .text-left
        a.navbar-brand href="#" Sports Hub
    .col-md-6.float-right
      .text-right.copyright
        | Copyright ©2020 Sport Hub
        br
        a href="#"
          strong Privacy / Terms

app/views/layouts/_header.html.slim
header class="border-bottom"
  nav class="border border-dark navbar navbar-white bg-white header-nav"
    div class="container-fluid"
      div class="navbar-header"
        button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"
          span class="sr-only" Toggle navigation
          span class="icon-bar"
          span class="icon-bar"
          span class="icon-bar"

        a class="navbar-brand header-brand" href="#" Sports Hub
      div class="" id="bs-examplertyh-navbar-coherllapse-1"
        - unless admin_namespace?
          form class="navbar-form navbar-left"
            div class="form-group"
              input type="text" class="form-control" placeholder="Search"

            button type="submit" class="btn btn-default" = t('search')
          ul class="nav navbar-nav"
            - if devise_mapping.omniauthable? && !user_signed_in?
              - resource_class.omniauth_providers.each do |provider|
                li
                  = link_to get_provider_url(provider) do
                    - if provider == :facebook
                      i class="fa fa-facebook fa-fw"
                    - if provider == :google_oauth2
                      i class="fa fa-google fa-fw"

        ul class="nav navbar-nav navbar-right border-left"
          - if user_signed_in?
            li
              li class="dropdown"
                a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
                  = t('profile')
                  span class="caret"
                ul class="dropdown-menu"
                  li
                    = link_to t('view_profile'), edit_user_registration_path
                  li
                    = link_to t('change_password'), edit_user_registration_path
                  li
                    = link_to t('my_surveys'), edit_user_registration_path
                  li
                    = link_to t('team_hub'), edit_user_registration_path
                  li role="separator" class="divider"
                  li
                    = button_to 'Log out', destroy_user_session_path, method: :delete
          - else
            li
              = link_to 'Login', new_user_session_url, class: 'login'
            li
              = link_to 'Sign Up', new_user_registration_path, class: 'sign-up'
          li
            ul class="nav navbar-nav border-left"
              - if user_signed_in?
                li
                  li class="dropdown"
                    a href="#" class="btn dropdown-toggle top-lang" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
                      = t(I18n.locale)
                    ul class="dropdown-menu"
                      - I18n.available_locales.each do |lang|
                        li
                          = link_to lang, current_page_params.merge(locale: lang.to_s)

app/views/layouts/_left-menu.html.slim
.col-lg-1
  .well.sidebar-nav
    ul.nav.nav-list.left-menu-list
      li.nav-header
      li= link_to "/path1" do
        i class='bi bi-chat-right-dots'
      li= link_to "/banners" do
          i class='bi bi-collection'
      li= link_to "/languages" do
          i class='bi bi-globe'
      li= link_to "/path1" do
        i class='bi bi-layout-text-window-reverse'
      li= link_to "/path1" do
        i class='bi bi-share'
      li= link_to admin_users_path do
        i class='bi bi-people'
      li= link_to admin_information_architecture_path do
          i class='bi bi-diagram-2'
      li= link_to "/teams" do
        i class='bi bi-card-text'
      li= link_to "/path1" do
        i class='bi bi-briefcase'
      li= link_to "/banners" do
        i class='bi bi-megaphone'

app/views/layouts/_top_menu.html.slim
.navbar-static-top.top-menu
  .scrollmenu
    a href="#{admin_root_path}" Home
    - get_categories.each do |category|
      = link_to category.name, admin_category_path(category)

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = @page_title ||= 'Sport Hub'
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"
    script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"
  body
    = render 'layouts/header'
    .container
      .row
        .col-lg-6
          h1 = @page_title
        - if @action_button_name.present? && @action_button_url.present?
          .col-lg-2.action-button
            = link_to @action_button_name,
                    @action_button_url,
                    class: 'btn ' + (@action_btn_save ? 'btn-action-save' : '')
        - if @action_cancel_button_name.present?
          .col-lg-2.action-cancel-button
            = link_to @action_cancel_button_name,
                    :back,
                    class: 'btn'
    = render 'layouts/top_menu' if admin_namespace?

    .row
      = render 'layouts/left-menu'
      .col-lg-10.main-content
        = bootstrap_flash
        = yield

    = render 'admin/shared/modals'
    = render 'layouts/footer' unless admin_namespace?